### ISSUE TITLE
Wiki and screenshot not there

### ISSUE THREAD

**Issue by mxmilkiib** [jimm/keymaster#1]
Hi, the links in the README aren't working atm.

**Comment by jimm** [comment]
> Hi, the links in the README aren't working atm.

Thanks for reporting this. When I was switching repo names around, I didn't complete the transition of the wiki. I will fix this as soon as I'm able, probably this weekend.

**Comment by jimm** [comment]
Fixed. The problem was that I changed the base branch's name from "master" to "main", as I have done with all of my repos. The Github wiki requires that the base branch name be "master". Renaming the branch and pushing the wiki repo fixed both the wiki content and the screenshot in KeyMaster's README.
